# Generated by Django 3.1.5 on 2021-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainGenre', models.CharField(default='', max_length=20)),
                ('secGenre', models.CharField(default='', max_length=20)),
                ('yearOfRelease', models.PositiveSmallIntegerField(default=2021)),
            ],
        ),
    ]
