# Generated by Django 3.1.5 on 2021-01-10 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='checkedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
    ]
